spring.application.name=SpringBoot3

#logging.level.org.springframework=debug

# Database Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries (very helpful for debugging JPA)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Set logging level for your package
logging.level.com.jpa.main=INFO

# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql